Create README_SWA.md
skydoves/android-developer-roadmap pull request #42
Opened 2022-10-09 09:50 UTC by mkaomwakuni

Added a Swahili Language Translation

## Guidelines
The Idea behind adding the Swahili Language Translation is to be able to allow understanding  of the android roadmap especially for the developers from Tanzania and several east African regions.

### Types of changes
What types of changes does your code introduce?

- [ ] Language (Swahili Translation)

### Preparing a pull request for review
Ensure your change is properly formatted by running:

```gradle
$ ./gradlew spotlessApply
```

Please correct any failures before requesting a review.

2022-10-09 10:29 UTC, skydoves requested changes
Hi @mkaomwakuni, thank you for your contribution!
Could you update other README files like the other PRs? You can reference: https://github.com/skydoves/android-developer-roadmap/pull/41

2022-10-09 10:29 UTC, skydoves commented on README_SWA.md
> +## 🗺 Ramani ya barabara
We can a new line here.

2022-10-09 11:52 UTC, mkaomwakuni reviewed
good

2024-02-12 13:00 UTC, skydoves approved these changes
Looks good to me!

2024-02-12 13:00 UTC, merged